// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server_app.Data;

#nullable disable

namespace server_app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250503164443_UpdateDoctorAcesses")]
    partial class UpdateDoctorAcesses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server_app.Models.DoctorAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("DoctorAccesses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12345678-1234-1234-1234-1234567890ab"),
                            ExpiresAt = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dr. Gregory House",
                            OwnerUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Revoked = false
                        },
                        new
                        {
                            Id = new Guid("87654321-4321-4321-4321-ba0987654321"),
                            ExpiresAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dr. Meredith Grey",
                            OwnerUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Revoked = false
                        });
                });

            modelBuilder.Entity("server_app.Models.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("RecordTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecordTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Date = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RecordTypeId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Title = "Complete Blood Count",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Date = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            RecordTypeId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Title = "Chest X-Ray",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Date = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            RecordTypeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Title = "Dermatology Consultation",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Date = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            RecordTypeId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Title = "Blood Pressure Medication",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Date = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RecordTypeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Title = "Appendectomy",
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("server_app.Models.MedicalRecordFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("MedicalRecordFiles");
                });

            modelBuilder.Entity("server_app.Models.RecordType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RecordTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "report"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "image"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "prescription"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "form"
                        });
                });

            modelBuilder.Entity("server_app.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EsculabPatientId")
                        .HasColumnType("text");

                    b.Property<string>("EsculabPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DateOfBirth = new DateTime(1985, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.smith@example.com",
                            FullName = "Alice Smith",
                            PasswordHash = "$2a$11$uG8v.z01UXD2DzTCKFTZP.U2r3koECkfjZg0Nbh3b6p5z1LGCb5BW",
                            PhoneNumber = "+380501234567"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DateOfBirth = new DateTime(1990, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.johnson@example.com",
                            FullName = "Bob Johnson",
                            PasswordHash = "$2a$11$uG8v.z01UXD2DzTCKFTZP.U2r3koECkfjZg0Nbh3b6p5z1LGCb5BW",
                            PhoneNumber = "+380509876543"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DateOfBirth = new DateTime(1978, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol.williams@example.com",
                            FullName = "Carol Williams",
                            PasswordHash = "$2a$11$uG8v.z01UXD2DzTCKFTZP.U2r3koECkfjZg0Nbh3b6p5z1LGCb5BW",
                            PhoneNumber = "+380503456789"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            DateOfBirth = new DateTime(2000, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.brown@example.com",
                            FullName = "David Brown",
                            PasswordHash = "$2a$11$uG8v.z01UXD2DzTCKFTZP.U2r3koECkfjZg0Nbh3b6p5z1LGCb5BW",
                            PhoneNumber = "+380507654321"
                        });
                });

            modelBuilder.Entity("server_app.Models.DoctorAccess", b =>
                {
                    b.HasOne("server_app.Models.User", "User")
                        .WithMany("DoctorAccesses")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server_app.Models.User", "SharedWithUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId");

                    b.Navigation("SharedWithUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server_app.Models.MedicalRecord", b =>
                {
                    b.HasOne("server_app.Models.RecordType", "RecordType")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("RecordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server_app.Models.User", "User")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server_app.Models.MedicalRecordFile", b =>
                {
                    b.HasOne("server_app.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("Files")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("server_app.Models.MedicalRecord", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("server_app.Models.RecordType", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("server_app.Models.User", b =>
                {
                    b.Navigation("DoctorAccesses");

                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
