// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server_app.Data;

#nullable disable

namespace server_app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server_app.Models.DoctorAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetUserEmail")
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("DoctorAccesses");
                });

            modelBuilder.Entity("server_app.Models.DoctorComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorAccessId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorCommentTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EsculabRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorAccessId");

                    b.HasIndex("DoctorCommentTypeId");

                    b.HasIndex("EsculabRecordId");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("DoctorComments");
                });

            modelBuilder.Entity("server_app.Models.DoctorCommentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DoctorCommentTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "prescription"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "reccomendations"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "comment"
                        });
                });

            modelBuilder.Entity("server_app.Models.EsculabRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Dt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdClient")
                        .HasColumnType("integer");

                    b.Property<int>("IdGrTest")
                        .HasColumnType("integer");

                    b.Property<int>("IdOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("Last")
                        .HasColumnType("boolean");

                    b.Property<string>("Packet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Ready")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StringAgg")
                        .HasColumnType("text");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EsculabRecords");
                });

            modelBuilder.Entity("server_app.Models.EsculabRecordDetails", b =>
                {
                    b.Property<Guid>("DetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EsculabRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("barcode")
                        .HasColumnType("text");

                    b.Property<int>("cnt")
                        .HasColumnType("integer");

                    b.Property<double>("height")
                        .HasColumnType("double precision");

                    b.Property<int>("id")
                        .HasColumnType("integer");

                    b.Property<int>("idOrder")
                        .HasColumnType("integer");

                    b.Property<int>("idOrdertest")
                        .HasColumnType("integer");

                    b.Property<int>("idgrnorm")
                        .HasColumnType("integer");

                    b.Property<int>("idgrtest")
                        .HasColumnType("integer");

                    b.Property<int>("idlaborant")
                        .HasColumnType("integer");

                    b.Property<int>("idtest")
                        .HasColumnType("integer");

                    b.Property<string>("laborant")
                        .HasColumnType("text");

                    b.Property<string>("material")
                        .HasColumnType("text");

                    b.Property<string>("norm")
                        .HasColumnType("text");

                    b.Property<string>("normheader")
                        .HasColumnType("text");

                    b.Property<string>("packet")
                        .HasColumnType("text");

                    b.Property<string>("patient")
                        .HasColumnType("text");

                    b.Property<DateTime?>("patientDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("patientId")
                        .HasColumnType("integer");

                    b.Property<string>("post")
                        .HasColumnType("text");

                    b.Property<int>("ready")
                        .HasColumnType("integer");

                    b.Property<string>("result")
                        .HasColumnType("text");

                    b.Property<int>("resultlighting")
                        .HasColumnType("integer");

                    b.Property<string>("resulttmlt")
                        .HasColumnType("text");

                    b.Property<string>("resulttype")
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .HasColumnType("text");

                    b.Property<string>("state")
                        .HasColumnType("text");

                    b.Property<string>("test")
                        .HasColumnType("text");

                    b.Property<string>("units")
                        .HasColumnType("text");

                    b.Property<DateTime?>("utime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DetailsId");

                    b.HasIndex("EsculabRecordId");

                    b.ToTable("EsculabRecordDetails");
                });

            modelBuilder.Entity("server_app.Models.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("RecordTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecordTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("server_app.Models.MedicalRecordFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("MedicalRecordFiles");
                });

            modelBuilder.Entity("server_app.Models.RecordType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RecordTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "report"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "image"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "prescription"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "form"
                        });
                });

            modelBuilder.Entity("server_app.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EsculabPatientId")
                        .HasColumnType("text");

                    b.Property<string>("EsculabPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("server_app.Models.DoctorAccess", b =>
                {
                    b.HasOne("server_app.Models.User", "User")
                        .WithMany("DoctorAccesses")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server_app.Models.User", "SharedWithUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId");

                    b.Navigation("SharedWithUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server_app.Models.DoctorComment", b =>
                {
                    b.HasOne("server_app.Models.DoctorAccess", "DoctorAccess")
                        .WithMany("DoctorComments")
                        .HasForeignKey("DoctorAccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server_app.Models.DoctorCommentType", "DoctorCommentType")
                        .WithMany("DoctorComments")
                        .HasForeignKey("DoctorCommentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server_app.Models.EsculabRecord", "EsculabRecord")
                        .WithMany("DoctorComments")
                        .HasForeignKey("EsculabRecordId");

                    b.HasOne("server_app.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("DoctorComments")
                        .HasForeignKey("MedicalRecordId");

                    b.Navigation("DoctorAccess");

                    b.Navigation("DoctorCommentType");

                    b.Navigation("EsculabRecord");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("server_app.Models.EsculabRecord", b =>
                {
                    b.HasOne("server_app.Models.User", "User")
                        .WithMany("EsculabRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server_app.Models.EsculabRecordDetails", b =>
                {
                    b.HasOne("server_app.Models.EsculabRecord", "EsculabRecord")
                        .WithMany("EsculabRecordDetails")
                        .HasForeignKey("EsculabRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EsculabRecord");
                });

            modelBuilder.Entity("server_app.Models.MedicalRecord", b =>
                {
                    b.HasOne("server_app.Models.RecordType", "RecordType")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("RecordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server_app.Models.User", "User")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server_app.Models.MedicalRecordFile", b =>
                {
                    b.HasOne("server_app.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("Files")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("server_app.Models.DoctorAccess", b =>
                {
                    b.Navigation("DoctorComments");
                });

            modelBuilder.Entity("server_app.Models.DoctorCommentType", b =>
                {
                    b.Navigation("DoctorComments");
                });

            modelBuilder.Entity("server_app.Models.EsculabRecord", b =>
                {
                    b.Navigation("DoctorComments");

                    b.Navigation("EsculabRecordDetails");
                });

            modelBuilder.Entity("server_app.Models.MedicalRecord", b =>
                {
                    b.Navigation("DoctorComments");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("server_app.Models.RecordType", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("server_app.Models.User", b =>
                {
                    b.Navigation("DoctorAccesses");

                    b.Navigation("EsculabRecords");

                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
