version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - PERSISTENCE=1
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  app:
    build: .
    environment:
      - AWS_REGION=us-east-1
      - AWS_SERVICE_URL=http://localstack:4566
    depends_on:
      - localstack
